# Generated by Django 5.2.7 on 2025-11-07 08:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_alter_snippet_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='code',
            field=models.TextField(max_length=5000, validators=[django.core.validators.MaxLengthValidator(5000)]),
        ),
    ]
